app = "multi-agent-finance-assistant"  # Replace with your Fly.io app name
primary_region = "bom"  # Replace with your preferred region

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[processes]
  app = "uvicorn orchestrator.main:app --host 0.0.0.0 --port 8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
